{
  "service": "auth-server",
  "provider": {
    "name": "aws",
    "runtime": "nodejs12.x",
    "region": "us-east-1",
    "timeout": "60"
},
"functions": {
  "getToken": {
    "handler": "handler.getToken",
    "environment": {
      "SLS_DEBUG": "true"
    },
    "events": [
      {
       "http": {
          "path": "api/token/{code}",
          "method": "get",
          "cors": "true"
       }
      }
    ]
  },
  "refreshToken": {
    "handler": "handler.refreshToken",
    "events": [
      {
        "http": {
          "path": "api/refresh/{code}",
          "method": "get",
          "cors": "true"
        }
      }
    ]
  }
}
}